---

name: Build Images and Upload to S3

on:
  push:
    branches:
      - main
    paths:
      - 'orgchart.pdf'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Create local changes
        run: |
          bash make_jpg.sh

      - name: sync to s3
        run: |
          aws s3 cp orgchart.jpg s3://res.starwarsccg.org/orgchart/
          aws s3 cp orgchart.pdf s3://res.starwarsccg.org/orgchart/
          aws cloudfront create-invalidation --distribution-id E4R02360UW5RJ --paths "/orgchart/orgchart.jpg" "/orgchart/orgchart.pdf"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Commit files
        run: |
          git config --local user.email "devon+github-actions[bot]@hubner.org"
          git config --local user.name "github-actions[bot]"
          git add -A .
          git commit -m "generated new images" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}


